### ISSUE TITLE
duplicate definitions in CSS

### ISSUE THREAD

**Issue by troubas** [substack/catw#5]
Hi

In this specific example I watch my CSS Files with the following command: 
`"watch-css": "catw app/main.css app/styles/* -o static/bundle.css -dv"`

I often run into the issue that when watching multiple css files with catw it creates a duplicate of certain definitions. For example:

The file is in this case `app/styles/login.css` with the following content:
``` css
#login-widget {
    position: absolute;
    top: 50px;
    right: 10px;
    width: 230px;
    height: 170px;

    margin: 5px;
    background-color: white;
    box-shadow: 0px 0px 2px black;

    transition: opacity .5s, z-index 1s;
}

#login-widget h3 {
    margin: 0px 0px 10px 0px;
}

#submit-login {
    float: right;
    margin-right: 0px;
}

#login-widget .IHW-init {
    margin: 10px 20px;
}
```
The `static/bundle.css` now has the following content 
``` css
#login-widget {
    position: absolute;
    top: 50px;
    right: 10px;
    width: 230px;
    height: 170px;

    margin: 5px;
    background-color: white;
    box-shadow: 0px 0px 2px black;

    transition: opacity .5s, z-index 1s;
}

#login-widget h3 {
    margin: 0px 0px 10px 0px;
}

#submit-login {
    float: right;
    margin-right: 0px;
}

#login-widget .IHW-init {
    margin: 10px 20px;
}
generates: 
#login-widget {
    position: absolute;
    top: 50px;
    right: 10px;
    width: 230px;
    height: 120px;

    margin: 5px;
    background-color: white;
    box-shadow: 0px 0px 2px black;

    transition: opacity .5s, z-index 1s;
}

#login-widget h3 {
    margin: 0px 0px 10px 0px;
}

#submit-login {
    float: right;
    margin-right: 0px;
}

#login-widget .IHW-init {
    margin: 10px 20px;
}
```

The unchanged version also annoyingly gets placed to the bottom (otherwhise I probably wouldn't have noticed it..) like so:
``` css
# Style Definition New
# Style Definition Old
```

Any ideas where I should start searching for the reason of this issue?
